### ISSUE TITLE
Getting error in IOS app

### ISSUE THREAD

**Issue by vishnuindrabalan** [ushelp/EasyQRCode-React-Native#1]
I tried installing the package in my react-native application **(IOS)** and getting some issues 
with RCTLinkingmanager.mm and RCTVibration.mm

Installed the package using `yarn add easyqrcode-react-native` and run `pod install` after successful package installation.

`react-native-webview` (version: 11.2.0) is already installed and auto-linked in my app so I skipped the below commands

> npm install react-native-webview
> react-native link react-native-webview

**My react-native version - 0.64.1**

Please let me know this package is compatible with react native IOS app with CocoaPods configuration.

While building I'm getting the below error

![image](https://user-images.githubusercontent.com/11517999/121772939-5534f900-cb96-11eb-8d28-5b95ae8e5079.png)

**Comment by vishnuindrabalan** [comment]
> I tried installing the package in my react-native application **(IOS)** and getting some issues
> with RCTLinkingmanager.mm and RCTVibration.mm
> 
> Installed the package using `yarn add easyqrcode-react-native` and run `pod install` after successful package installation.
> 
> `react-native-webview` (version: 11.2.0) is already installed and auto-linked in my app so I skipped the below commands
> 
> > npm install react-native-webview
> > react-native link react-native-webview
> 
> **My react-native version - 0.64.1**
> 
> Please let me know this package is compatible with react native IOS app with CocoaPods configuration.
> 
> While building I'm getting the below error
> 
> ![image](https://user-images.githubusercontent.com/11517999/121772939-5534f900-cb96-11eb-8d28-5b95ae8e5079.png)

Solved this issue by adding `react-native-svg`  package.

>yarn add  react-native-svg

@ushelp can we please update the readme if it's  (react-native-svg ) a peer dependency?

**Comment by ushelp** [comment]
Sorry for responding too late, and glad that you have sloved the issue yourself.

But I want to know more detail about the issue, Why did `react-native-svg` slove your issue, because our code not use svg function.

Hope get your reply for your investgation.

**Comment by ushelp** [comment]
@vishnuindrabalan Looking forward to your reply.

**Comment by vishnuindrabalan** [comment]
Hi @ushelp  sorry for the late response.
I didn't check the issue in detail, so I cannot explain how the `react-native-svg` package fixed the issue.
I was parallelly checking some other package and all those have SVG package as a peer dependency, so I tried installing that and the error is gone. Maybe some of the packages which you are using internally might required SVG package.

**Comment by ushelp** [comment]
Thank you for your reply.
